# Generated by Django 5.2.8 on 2025-11-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Mlibro',
        ),
    ]
